# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3733146f6c267363f38efab9426f45e7fdd2be93225ce0fb3e49bb4035d9a0e40c4d83a1dd42eac7274e64a6b1c382b397dd4611b079d2202668d58dff5c8f49

test:
  secret_key_base: f89c8d39a0ca17b99f70fe9543dc17bb3b54d7bd0c74ed63f35754473cfc9fc4d27ce6a5eb64ccd77a864e063733dba39db848308ee64fd74d9671172395fb23

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
